export const mailInboxdata = [
  {
    ID: 1,
    CUSTOMER_MAIL_ID: "one@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV1",
    CREATION: "18-03-2024",
  },
  {
    ID: 2,
    CUSTOMER_MAIL_ID: "two@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV2",
    CREATION: "18-03-2024",
  },
  {
    ID: 3,
    CUSTOMER_MAIL_ID: "three@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV3",
    CREATION: "18-03-2024",
  },
  {
    ID: 4,
    CUSTOMER_MAIL_ID: "four@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV4",
    CREATION: "18-03-2024",
  },
  {
    ID: 5,
    CUSTOMER_MAIL_ID: "five@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV5",
    CREATION: "18-03-2024",
  },
  {
    ID: 6,
    CUSTOMER_MAIL_ID: "six@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV6",
    CREATION: "18-03-2024",
  },
  {
    ID: 7,
    CUSTOMER_MAIL_ID: "seven@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV7",
    CREATION: "18-03-2024",
  },
  {
    ID: 8,
    CUSTOMER_MAIL_ID: "eight@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV8",
    CREATION: "18-03-2024",
  },
  {
    ID: 9,
    CUSTOMER_MAIL_ID: "nine@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV9",
    CREATION: "18-03-2024",
  },
  {
    ID: 10,
    CUSTOMER_MAIL_ID: "ten@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV10",
    CREATION: "18-03-2024",
  },
  {
    ID: 11,
    CUSTOMER_MAIL_ID: "eleven@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV11",
    CREATION: "18-03-2024",
  },
  {
    ID: 12,
    CUSTOMER_MAIL_ID: "twelve@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV12",
    CREATION: "18-03-2024",
  },
  {
    ID: 13,
    CUSTOMER_MAIL_ID: "thirteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV13",
    CREATION: "18-03-2024",
  },
  {
    ID: 14,
    CUSTOMER_MAIL_ID: "fourteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV14",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 1,
    CUSTOMER_MAIL_ID: "one@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV1",
    CREATION: "18-03-2024",
  },
  {
    ID: 2,
    CUSTOMER_MAIL_ID: "two@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV2",
    CREATION: "18-03-2024",
  },
  {
    ID: 3,
    CUSTOMER_MAIL_ID: "three@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV3",
    CREATION: "18-03-2024",
  },
  {
    ID: 4,
    CUSTOMER_MAIL_ID: "four@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV4",
    CREATION: "18-03-2024",
  },
  {
    ID: 5,
    CUSTOMER_MAIL_ID: "five@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV5",
    CREATION: "18-03-2024",
  },
  {
    ID: 6,
    CUSTOMER_MAIL_ID: "six@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV6",
    CREATION: "18-03-2024",
  },
  {
    ID: 7,
    CUSTOMER_MAIL_ID: "seven@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV7",
    CREATION: "18-03-2024",
  },
  {
    ID: 8,
    CUSTOMER_MAIL_ID: "eight@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV8",
    CREATION: "18-03-2024",
  },
  {
    ID: 9,
    CUSTOMER_MAIL_ID: "nine@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV9",
    CREATION: "18-03-2024",
  },
  {
    ID: 10,
    CUSTOMER_MAIL_ID: "ten@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV10",
    CREATION: "18-03-2024",
  },
  {
    ID: 11,
    CUSTOMER_MAIL_ID: "eleven@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV11",
    CREATION: "18-03-2024",
  },
  {
    ID: 12,
    CUSTOMER_MAIL_ID: "twelve@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV12",
    CREATION: "18-03-2024",
  },
  {
    ID: 13,
    CUSTOMER_MAIL_ID: "thirteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV13",
    CREATION: "18-03-2024",
  },
  {
    ID: 14,
    CUSTOMER_MAIL_ID: "fourteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV14",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 1,
    CUSTOMER_MAIL_ID: "one@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV1",
    CREATION: "18-03-2024",
  },
  {
    ID: 2,
    CUSTOMER_MAIL_ID: "two@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV2",
    CREATION: "18-03-2024",
  },
  {
    ID: 3,
    CUSTOMER_MAIL_ID: "three@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV3",
    CREATION: "18-03-2024",
  },
  {
    ID: 4,
    CUSTOMER_MAIL_ID: "four@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV4",
    CREATION: "18-03-2024",
  },
  {
    ID: 5,
    CUSTOMER_MAIL_ID: "five@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV5",
    CREATION: "18-03-2024",
  },
  {
    ID: 6,
    CUSTOMER_MAIL_ID: "six@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV6",
    CREATION: "18-03-2024",
  },
  {
    ID: 7,
    CUSTOMER_MAIL_ID: "seven@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV7",
    CREATION: "18-03-2024",
  },
  {
    ID: 8,
    CUSTOMER_MAIL_ID: "eight@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV8",
    CREATION: "18-03-2024",
  },
  {
    ID: 9,
    CUSTOMER_MAIL_ID: "nine@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV9",
    CREATION: "18-03-2024",
  },
  {
    ID: 10,
    CUSTOMER_MAIL_ID: "ten@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV10",
    CREATION: "18-03-2024",
  },
  {
    ID: 11,
    CUSTOMER_MAIL_ID: "eleven@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV11",
    CREATION: "18-03-2024",
  },
  {
    ID: 12,
    CUSTOMER_MAIL_ID: "twelve@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV12",
    CREATION: "18-03-2024",
  },
  {
    ID: 13,
    CUSTOMER_MAIL_ID: "thirteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV13",
    CREATION: "18-03-2024",
  },
  {
    ID: 14,
    CUSTOMER_MAIL_ID: "fourteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV14",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 1,
    CUSTOMER_MAIL_ID: "one@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV1",
    CREATION: "18-03-2024",
  },
  {
    ID: 2,
    CUSTOMER_MAIL_ID: "two@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV2",
    CREATION: "18-03-2024",
  },
  {
    ID: 3,
    CUSTOMER_MAIL_ID: "three@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV3",
    CREATION: "18-03-2024",
  },
  {
    ID: 4,
    CUSTOMER_MAIL_ID: "four@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV4",
    CREATION: "18-03-2024",
  },
  {
    ID: 5,
    CUSTOMER_MAIL_ID: "five@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV5",
    CREATION: "18-03-2024",
  },
  {
    ID: 6,
    CUSTOMER_MAIL_ID: "six@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV6",
    CREATION: "18-03-2024",
  },
  {
    ID: 7,
    CUSTOMER_MAIL_ID: "seven@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV7",
    CREATION: "18-03-2024",
  },
  {
    ID: 8,
    CUSTOMER_MAIL_ID: "eight@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV8",
    CREATION: "18-03-2024",
  },
  {
    ID: 9,
    CUSTOMER_MAIL_ID: "nine@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV9",
    CREATION: "18-03-2024",
  },
  {
    ID: 10,
    CUSTOMER_MAIL_ID: "ten@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV10",
    CREATION: "18-03-2024",
  },
  {
    ID: 11,
    CUSTOMER_MAIL_ID: "eleven@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV11",
    CREATION: "18-03-2024",
  },
  {
    ID: 12,
    CUSTOMER_MAIL_ID: "twelve@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV12",
    CREATION: "18-03-2024",
  },
  {
    ID: 13,
    CUSTOMER_MAIL_ID: "thirteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV13",
    CREATION: "18-03-2024",
  },
  {
    ID: 14,
    CUSTOMER_MAIL_ID: "fourteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV14",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
  {
    ID: 15,
    CUSTOMER_MAIL_ID: "fifteen@one.com",
    MESSAGE: "Hello World",
    ORDER_ID: "ABC123",
    INVOICE: "INV15",
    CREATION: "18-03-2024",
  },
];

export const mailHeader = [
  {
    Header: "Customer Mail Id",
    accessor: "CUSTOMER_MAIL_ID",
    className: "text-center wd-15p border-bottom-0 ",
  },
  {
    Header: "Message",
    accessor: "MESSAGE",
    className: "text-center wd-15p border-bottom-0 ",
  },
  {
    Header: "Order Id",
    accessor: "ORDER_ID",
    className: "text-center wd-15p border-bottom-0 ",
  },
  {
    Header: "Invoice",
    accessor: "INVOICE",
    className: "text-center wd-15p border-bottom-0 ",
    Cell: ({ row }) => (
      <button
        onClick={() => {
          alert(
            `Invoice with invoice id ${row.original.INVOICE} was downloading which was sent by user with id ${row.original.CUSTOMER_MAIL_ID}`
          );
        }}
        className={`inventory_product_image`}
      >
        <i className="fa fa-download text-primary"></i>
      </button>
    ),
  },
  {
    Header: "Creation",
    accessor: "CREATION",
    className: "text-center wd-15p border-bottom-0 ",
  },
];
